### ISSUE TITLE
Need to add 6th Section

### ISSUE THREAD

**Issue by pvenkateshnaidu** [tirumalasrija/writerclub-codebase#8]
Need to add new carousel to scroll stories
![91315652-f37ddc80-e785-11ea-83b9-e93084371632](https://user-images.githubusercontent.com/19386308/91415870-3ca85c00-e86c-11ea-9666-74a6ac9b87b0.png)

**Comment by tirumalasrija** [comment]
* I am trying to click on "Read more" it is not allowing
* carousel should show clearly with color
